image: docker:latest

stages:
- build
- release

variables:
  CONTAINER_TEST_IMAGE: gitlab-registry.cern.ch/fts/fts3:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: gitlab-registry.cern.ch/fts/fts3:latest

before_script:
    - docker info
    - docker login -p "${REGISTRY_PASSWD}" -u "${REGISTRY_USER}" gitlab-registry.cern.ch
    
after_script:
    - docker logout gitlab-registry.cern.ch

build:
    stage: build
    script:
      - docker build --pull -t $CONTAINER_TEST_IMAGE packaging/docker
      - docker push $CONTAINER_TEST_IMAGE

master:
    stage: release
    only:
        - master
    script:
        - docker pull $CONTAINER_TEST_IMAGE
        - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
        - docker push $CONTAINER_RELEASE_IMAGE
    tags:
        - docker 
