stages:
- build
- docker
- tag

#--------------------------
# Docker build jobs
#--------------------------

.docker_build:
    stage: docker
    only:
      - develop
    script:
      - ""
    variables:
      TO: gitlab-registry.cern.ch/fts/fts3:latest
      DOCKER_FILE:  packaging/docker/Dockerfile
    tags:
      - docker-image-build

.docker_tag:
    stage: tag
    only:
      - tags
    script:
      - ""
    variables:
      TO: gitlab-registry.cern.ch/fts/fts3:$CI_BUILD_REF_NAME
      DOCKER_FILE:  packaging/docker/Dockerfile-release
    tags:
      - docker-image-build
