image: docker:latest

before_script:
    - docker info
    - docker login -p "${REGISTRY_PASSWD}" -u "${REGISTRY_USER}" gitlab-registry.cern.ch
    
after_script:
    - docker logout gitlab-registry.cern.ch

master:
    only:
        - master
    script:
        - docker build -t  gitlab-registry.cern.ch/fts/fts3:master packaging/docker
        - docker push gitlab-registry.cern.ch/fts/fts3
    tags:
        - docker 
