stages:
- build
- tag

variables:
  CONTAINER_TEST_IMAGE: gitlab-registry.cern.ch/fts/fts3:latest
  CONTAINER_RELEASE_IMAGE: gitlab-registry.cern.ch/fts/fts3:$CI_BUILD_REF_NAME

build:
    stage: build
    only:
      - develop
    script:
      - ""
    variables:
      TO: $CONTAINER_TEST_IMAGE
      DOCKER_FILE:  packaging/docker/Dockerfile
    tags:
      - docker-image-build
tag:
    stage: tag
    only:
        - tags
    script:
      - ""
    variables:
      TO: $CONTAINER_RELEASE_IMAGE
      DOCKER_FILE:  packaging/docker/Dockerfile
    tags:
        - docker-image-build

